### ISSUE TITLE
CultureMinistry.createElement returns empty string when the first character is whitespace

### ISSUE THREAD

**Issue by scriptype** [dashersw/politburo#3]
In cultures, if I return a string whose first character is a whitespace like this:

```
template() {
  return `
    <div>lorem</div>
  `
}
```

It renders nothing and when I call `this.$()` somewhere else, it gives me this error:

![image](https://cloud.githubusercontent.com/assets/5516876/22174001/067f9e48-dfe4-11e6-87f4-2bcb52a00c3e.png)

I investigated the issue a little bit and found that `CultureMinistry.createElement` returns `firstChild` of the produced DOM structure, which happens to be whitespace in this case. It can return `firstElementChild` to fix the issue, but that would prohibit returning bare `textNodes` from template().

**Comment by dashersw** [comment]
Interesting! I think a string trim would solve this issue.

**Comment by scriptype** [comment]
Agreed, trim the string before setting innerHTML; rest of the code would stay the same.
